# Generated by Django 3.1.2 on 2020-10-26 20:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Namespace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('keyword', models.CharField(max_length=32, primary_key=True, serialize=False, unique=True)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('storage_duration', models.IntegerField(choices=[(0, '6h'), (1, '1d'), (2, '7d')], default=0)),
                ('password', models.CharField(blank=True, max_length=32)),
                ('text', models.TextField(blank=True, default='', max_length=100000)),
                ('file', models.FileField(blank=True, upload_to='files/<django.db.models.fields.CharField>/')),
                ('namespace', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.namespace')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
