# Generated by Django 3.1.2 on 2020-10-19 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('keyword', models.CharField(max_length=32, primary_key=True, serialize=False, unique=True)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('storage_duration', models.IntegerField(choices=[(0, '6h'), (1, '1d'), (2, '7d')], default=0)),
                ('password', models.CharField(blank=True, max_length=32)),
                ('text', models.TextField(blank=True, default='', max_length=100000)),
                ('file', models.FileField(blank=True, upload_to='files/<django.db.models.fields.CharField>/')),
            ],
        ),
    ]
