# Generated by Django 3.1.2 on 2020-10-10 13:23

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', tinymce.models.HTMLField()),
                ('keyword', models.CharField(max_length=32)),
                ('use_password', models.BooleanField(default=False)),
                ('password', models.CharField(blank=True, max_length=32)),
                ('file', models.FileField(blank=True, upload_to='files')),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
