# Generated by Django 3.1.2 on 2020-10-10 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='use_password',
        ),
        migrations.AddField(
            model_name='post',
            name='storage_duration',
            field=models.IntegerField(choices=[(0, '6h'), (1, '1d'), (1, '7d')], default=0),
        ),
        migrations.AlterField(
            model_name='post',
            name='keyword',
            field=models.CharField(max_length=32, unique=True),
        ),
    ]
