# Generated by Django 3.1.2 on 2020-10-10 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20201010_1828'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='id',
        ),
        migrations.AlterField(
            model_name='post',
            name='keyword',
            field=models.CharField(max_length=32, primary_key=True, serialize=False, unique=True),
        ),
    ]
