# Generated by Django 3.1.2 on 2020-10-18 16:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20201018_1142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='storage_duration',
            field=models.IntegerField(choices=[(datetime.timedelta(seconds=21600), '6h'), (datetime.timedelta(days=1), '1d'), (datetime.timedelta(days=7), '7d')], default=0),
        ),
    ]
